name: with_options_example
description: Comprehensive example with all HTTP function options
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  firebase_functions:
    path: ../../

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^6.0.0
