name: firebase_functions
description: Firebase Functions runtime for Dart - Write serverless functions in Dart with type safety and performance
version: 0.1.0
repository: https://github.com/invertase/firebase-functions-dart
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.2
  meta: ^1.18.0
  dart_firebase_admin:
    path: ../dart_firebase_admin/packages/dart_firebase_admin
  googleapis_firestore:
    path: ../dart_firebase_admin/packages/googleapis_firestore
  protobuf: ^6.0.0
  http: ^1.6.0
  jose: ^0.3.5
  # Required for builder
  build: ^4.0.4
  source_gen: ^4.2.0
  analyzer: ^10.0.1
  glob: ^2.1.3

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
  mocktail: ^1.0.4
  lints: ^6.0.0
  yaml: ^3.1.3

dependency_overrides:
  googleapis_firestore:
    path: ../dart_firebase_admin/packages/googleapis_firestore
  googleapis_auth_utils:
    path: ../dart_firebase_admin/packages/googleapis_auth_utils
  googleapis_storage:
    path: ../dart_firebase_admin/packages/googleapis_storage
