name: firestore_test
description: Test example for Firestore triggers
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  firebase_functions:
    path: ../../

dev_dependencies:
  build_runner: ^2.4.0
