name: firestore_test
description: Test example for Firestore triggers
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  firebase_functions: any

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
  http: ^1.6.0
  lints: ^6.0.0
