name: firestore_test
description: Test example for Firestore triggers
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  firebase_functions:
    path: ../../

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
  http: ^1.6.0
  lints: ^6.0.0

dependency_overrides:
  googleapis_firestore:
    path: ../../../dart_firebase_admin/packages/googleapis_firestore
  googleapis_auth_utils:
    path: ../../../dart_firebase_admin/packages/googleapis_auth_utils
  googleapis_storage:
    path: ../../../dart_firebase_admin/packages/googleapis_storage
