name: example

environment:
  sdk: ^3.11.0

dependencies:
  firebase_functions:
    path: ../../
  firebase_functions_genkit:
    path: ../
  genkit: ^0.10.0-dev.8
  genkit_google_genai: ^0.0.1-dev.8
  schemantic: ^0.0.1-dev.9

dependency_overrides: 
  analyzer: ^10.0.1
  dart_firebase_admin: ^0.4.1
  genkit: ^0.10.0-dev.2
  googleapis_auth: ^1.3.0
  protobuf: ^6.0.0
