name: example

environment:
  sdk: ^3.11.0

dependencies:
  firebase_functions_genkit:
    path: ../
  genkit: ^0.10.0-dev.8
  genkit_google_genai: ^0.0.1-dev.8
  json_schema_builder: ^0.1.3
  schemantic: ^0.0.1-dev.9
  firebase_functions:
    path: ../../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0

dependency_overrides: 
  analyzer: ^10.0.1
  protobuf: ^6.0.0
  dart_firebase_admin: ^0.4.1
  googleapis_auth: ^1.3.0
  genkit: ^0.10.0-dev.2