name: firebase_functions_genkit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0-17.0.dev

# Add regular dependencies here.
dependencies:
  firebase_functions:
    path: ../
  genkit:
    git:
      url: https://github.com/genkit-ai/genkit-dart/
      path: packages/genkit
  meta: ^1.18.0

dependency_overrides: 
  source_gen: ^4.1.0
  build: ^4.0.4
  analyzer: ^10.0.1
  protobuf: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
